In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('CarPrice.csv')
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [5]:
[df[col].unique() for col in df.columns]

[array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [9]:
list = ['fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'enginetype',
       'cylindernumber', 'fuelsystem']
for col in list:
    enc = LabelEncoder()
    df[col] = df[col].astype('category')
    encoded = enc.fit_transform(df[[col]])
    df[col] = encoded

C:\Users\admin\miniconda3\envs\ML_Internship\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\admin\miniconda3\envs\ML_Internship\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\admin\miniconda3\envs\ML_Internship\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\admin\miniconda3\envs\ML_Internship\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-v

In [10]:
df.info()
df['price'] = df['price'].astype('int')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    int32  
 4   aspiration        205 non-null    int32  
 5   doornumber        205 non-null    int32  
 6   carbody           205 non-null    int32  
 7   drivewheel        205 non-null    int32  
 8   enginelocation    205 non-null    int32  
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    int32  
 15  cylindernumber    205 non-null    int32  
 16  enginesize        205 non-null    int64  
 1

In [11]:
[df['fuelsystem'].unique() for col in df.columns]

[array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6]),
 array([5, 1, 4, 0, 7, 2, 3, 6])]

In [20]:
x = df.drop(['car_ID','CarName','symboling','price','wheelbase','carlength','carwidth','carheight','curbweight','enginesize','boreratio','stroke'],axis=1)
pd.set_option('display.max_columns', None)
x.head()
x.columns
x[x['enginelocation']!=0]
x
#fueltype gas=1,diesel=0
#aspiration standard=1,turbo=0
#doornumber two=1, four=0
#carbody convertible=0,hardtop=1,hatchback=2,sedan=3,wagon=4
#drivewheel rearwheeldrive=2,front wheel drive=1, 4 wheel drive=0
#enginelocation front=0,rear=1
#enginetype dual overhead camshaft(dohc)=0, overhead camshaft valve(ohcv)=5, overhead camshaft(ohc)=3, l=2, rotor=6, ohcf=4, dohcv=1
#cylindernumber 4cylinders=2,6cylinder=3,5cylinder=1,3c=4,12c=5,2c=6,8c=0
#fuelsystem mpfi=5,2bbl=1,mfi=4,1bbl=0,spfi=7,4bbl=2,id=3,spdi=6

print(x['highwaympg'].min())
print(x['highwaympg'].max())
print(x)

16
54
     fueltype  aspiration  doornumber  carbody  drivewheel  enginelocation  \
0           1           0           1        0           2               0   
1           1           0           1        0           2               0   
2           1           0           1        2           2               0   
3           1           0           0        3           1               0   
4           1           0           0        3           0               0   
..        ...         ...         ...      ...         ...             ...   
200         1           0           0        3           2               0   
201         1           1           0        3           2               0   
202         1           0           0        3           2               0   
203         0           1           0        3           2               0   
204         1           1           0        3           2               0   

     enginetype  cylindernumber  fuelsystem  compressionr

In [33]:
y = df[['price']]
y.head()

price
0  13495
1  16500
2  16500
3  13950
4  17450

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=101)
x_train.head()

fueltype  aspiration  doornumber  carbody  drivewheel  enginelocation  \
154         1           0           0        4           0               0   
74          1           0           1        1           2               0   
179         1           0           1        2           2               0   
118         1           0           1        2           1               0   
16          1           0           1        3           2               0   

     enginetype  cylindernumber  fuelsystem  compressionratio  horsepower  \
154           3               2           1               9.0          62   
74            5               0           5               8.0         184   
179           0               3           5               9.3         161   
118           3               2           1               9.4          68   
16            3               3           5               8.0         182   

     peakrpm  citympg  highwaympg  
154     4800       27          32  
74      4500       14          16  
179     5200       19          24  
118     5500       37          41  
16      5400       16          22

In [35]:
#from sklearn.tree import DecisionTreeClassifier
#model = DecisionTreeClassifier()
#model.fit(x_train,y_train)

In [36]:
#predictions = model.predict(x_test)
#predictions
#X=df[['fueltype', 'aspiration',
#       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
#       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
#       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
#       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg']]
#y=df[['price']]

#X_train,X_Test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [37]:
#from sklearn.metrics import r2_score
#r2_score(y_test,predictions)
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

predictions=model.predict(x_test)
#print(predictions)

y_pred = model.predict(x_test)
from sklearn.metrics import r2_score
print(r2_score(y_true=y_test, y_pred=y_pred))

0.6908180332907526


In [38]:
#from sklearn.metrics import accuracy_score
#accuracy_score(y_test,predictions)

In [40]:
import joblib
joblib.dump(model,'car-price-predictor')

['car-price-predictor']